valor = 'Juan'; 
console.log(`typeof ${valor} = ${typeof valor}`);
valor = 20; 
console.log(`typeof ${valor} = ${typeof valor}`);
valor = '20'; 
console.log(`typeof '${valor}' = ${typeof valor}`);
valor = 20.97; 
console.log(`typeof ${valor} = ${typeof valor}`);
valor = 123456789012345678901234567890; 
console.log(`typeof ${valor} = ${typeof valor}`);
valor = -12345.12345; 
console.log(`typeof ${valor} = ${typeof valor}`);
valor = false; 
console.log(`typeof ${valor} = ${typeof valor}`);
console.log('-----'); 
let valor2;
console.log('let valor2;'); 
console.log(`typeof valor2 = ${typeof valor2}`);
console.log(`(typeof valor2 === 'undefined') = ${typeof valor2 === 'undefined'}`);
console.log(`(typeof valor2 == 'undefined') = ${typeof valor2 == 'undefined'}`);
console.log(`(typeof valor2 === 'object') = ${typeof valor2 === 'object'}`);
console.log(`(typeof valor2 == 'object') = ${typeof valor2 == 'object'}`);
console.log('-----'); 
let valor3 = null;
console.log('let valor3 = null;'); 
console.log(`typeof valor3 = ${typeof valor3}`);
console.log(`typeof null = ${typeof null}`);
console.log(`(typeof valor3 === 'object') = ${typeof valor3 === 'object'}`);
console.log(`(typeof valor3 == 'object') = ${typeof valor3 == 'object'}`);
console.log('-----'); 
let valor4 = Symbol('valor4');
console.log(`let valor4 = Symbol('valor4');`); 
console.log(`typeof valor4 = ${typeof valor4}`);
console.log('-----'); 
let valor5 = [1,2,3,4,5];
console.log(`let valor5 = [1,2,3,4,5];`);
console.log(`typeof valor5 = ${typeof valor5}`);
console.log('-----'); 
let valor6 = { nombre: 'Zinedine', puesto: 'entrenador', sueldo: 7000000 };
console.log(`let valor6 = { nombre: 'Zinedine', puesto: 'entrenador', sueldo: 7000000 };`);
console.log(`typeof valor6 = ${typeof valor6}`);
console.log('-----'); 
let valor7 = new Date();
console.log(`let valor7 = new Date();`);
console.log(`valor7 = ${valor7}`);
console.log(`typeof valor7 = ${typeof valor7}`);
