let tecnologia = 'Javascript';
let alabanza = tecnologia.concat(' ', 'es genial', '!!!');

console.log(`Javascript.length => ${tecnologia.length}`);
console.log(`Javascript.concat(' ', 'es genial', '!!!') => ${alabanza}`);
console.log(`Javascript.toUpperCase() => ${tecnologia.toUpperCase()}`);
console.log(`Javascript.toLowerCase() => ${tecnologia.toLowerCase()}`);
console.log(`Javascript.indexOf('script') => ${tecnologia.indexOf('script')}`);
console.log(`Javascript.indexOf('Script') => ${tecnologia.indexOf('Script')}`);
console.log(`Javascript.indexOf('a') => ${tecnologia.indexOf('a')}`);
console.log(`Javascript.substring(0, 4) => ${tecnologia.substring(0, 4)}`);
console.log(`Javascript.substring(0, -4) => ${tecnologia.substring(0, -4)}`);
console.log(`Javascript.substring(1, 4) => ${tecnologia.substring(1, 4)}`);
console.log(`Javascript.substring(4) => ${tecnologia.substring(4)}`);
console.log(`Javascript.slice(0, 4) => ${tecnologia.slice(0, 4)}`);
console.log(`Javascript.slice(1, 4) => ${tecnologia.slice(1, 4)}`);
console.log(`Javascript.slice(4) => ${tecnologia.slice(4)}`);
console.log(`Javascript.slice(-1, 4) => ${tecnologia.slice(-1, 4)}`);
console.log(`Javascript.slice(0, -4) => ${tecnologia.slice(0, -4)}`);
console.log(`Javascript.slice(0, -1) => ${tecnologia.slice(0, -1)}`);
console.log(`Javascript.slice(-1, -4) => ${tecnologia.slice(-1, -4)}`);
console.log(`Javascript.slice(-4, -1) => ${tecnologia.slice(-4, -1)}`);
console.log(`Javascript.slice(1, -4) => ${tecnologia.slice(1, -4)}`);
console.log(`Javascript.slice(-4) => ${tecnologia.slice(-4)}`);
console.log(`Javascript.split('a') => ${tecnologia.split('a')}`)
console.log(`Javascript.replace('a', 'X') => ${tecnologia.replace('a', 'X')}`)
console.log(`Javascript.replace(/a/g, 'X') => ${tecnologia.replace(/a/g, 'X')}`)
console.log(`Javascript.replace('j', 'X') => ${tecnologia.replace('j', 'X')}`)
console.log(`Javascript.replace(/j/i, 'X') => ${tecnologia.replace(/j/i, 'X')}`)
console.log(`Javascript.includes('script') => ${tecnologia.includes('script')}`);
console.log(`Javascript.includes('Script') => ${tecnologia.includes('Script')}`);
console.log(`Javascript.repeat(3) => ${tecnologia.repeat(3)}`);
